title: Becoming Tech Librarian
description: > # this means to ignore newlines until "baseurl:"
  Librarianship Journey
permalink: '/:title/'

# Author settings
author: Tori
author-pic: yosh-ginsu.jpg
about-author: Learning to be a Tech Librarian

# Contact links
email: torirobinson@wayne.edu
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: tori-robinson61822 # Add your Linkedin handle
github: https://torobin.github.io/ #Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /blog/page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
colors: ["linear-gradient(90deg, red, white,red)", "linear-gradient(90deg, orange, white,orange)", "linear-gradient(90deg, yellow, white,yellow)",
"linear-gradient(90deg, green, white,green)", "linear-gradient(90deg, blue, white, blue)", "linear-gradient(90deg, purple, white,purple)"]
